export const GET_VISITED_PLACES = "GET_VISITED_PLACES";
export const GET_VISITED_PLACES_SUCCESS = "GET_VISITED_PLACES_SUCCESS";
export const GET_VISITED_PLACES_FAILED = "GET_VISITED_PLACES_FAILED";

export const SET_VISITED_PLACE = "SET_VISITED_PLACE";
export const SET_VISITED_PLACE_SUCCESS = "SET_VISITED_PLACE_SUCCESS";
export const SET_VISITED_PLACE_FAILED = "SET_VISITED_PLACE_FAILED";

export default GET_VISITED_PLACES;